/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.jni.core;

public class SwigPasswordCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SwigPasswordCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwigPasswordCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_SwigPasswordCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    otapiJNI.SwigPasswordCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    otapiJNI.SwigPasswordCallback_change_ownership(this, swigCPtr, true);
  }

  public SwigPasswordCallback() {
    this(otapiJNI.new_SwigPasswordCallback(), true);
    otapiJNI.SwigPasswordCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean SwigGetPassword(OTPassword passwordObject, String strMessage) {
    return (getClass() == SwigPasswordCallback.class) ? otapiJNI.SwigPasswordCallback_SwigGetPassword(swigCPtr, this, OTPassword.getCPtr(passwordObject), passwordObject, strMessage) : otapiJNI.SwigPasswordCallback_SwigGetPasswordSwigExplicitSwigPasswordCallback(swigCPtr, this, OTPassword.getCPtr(passwordObject), passwordObject, strMessage);
  }

  public boolean SwigNewPassword(OTPassword passwordObject, String strMessage) {
    return (getClass() == SwigPasswordCallback.class) ? otapiJNI.SwigPasswordCallback_SwigNewPassword(swigCPtr, this, OTPassword.getCPtr(passwordObject), passwordObject, strMessage) : otapiJNI.SwigPasswordCallback_SwigNewPasswordSwigExplicitSwigPasswordCallback(swigCPtr, this, OTPassword.getCPtr(passwordObject), passwordObject, strMessage);
  }

  public static boolean GetPassword(OTPassword passwordObject, String strMessage) {
    return otapiJNI.SwigPasswordCallback_GetPassword(OTPassword.getCPtr(passwordObject), passwordObject, strMessage);
  }

  public static boolean NewPassword(OTPassword passwordObject, String strMessage) {
    return otapiJNI.SwigPasswordCallback_NewPassword(OTPassword.getCPtr(passwordObject), passwordObject, strMessage);
  }

  public static boolean SetCallback(SwigPasswordCallback pSwigPasswordCallback) {
    return otapiJNI.SwigPasswordCallback_SetCallback(SwigPasswordCallback.getCPtr(pSwigPasswordCallback), pSwigPasswordCallback);
  }

}
