#!/bin/bash



FTNYM='DYEB6U7dcpbwdGrftPnslNKz76BDuBTFAjiAgKaiY2n'
BOBNYM='HpDoVBTix9GRLvZZoKBi2zv2f4IFVLmRrW2Q0nAA0OH'

FTACCT='yQGh0vgm9YiqYOh6bfLDxyAA7Nnh2NmturCQmOt4LTo'
BOBACCT='O8uUtFNyeKUqYdaBrroDR9OIgPhvtW91iBBVNEfbHDC'

SILVERPURSE='JY7kEFnm2c50CGNphdpgnlVo2hOZuLrBua5cFqWWR9Q'
TOKENSPURSE='7f8nlUn795x8931JParRnmKAyw8cegRyBMcFg9FccaF'

SERVER='r1fUoHwJOWCuK3WBAAySjmKYqsG6G2TYIxdqY6YNuuG'

echo ""
echo "WARNING: this script often requires you to copy and paste back whatever financial instrument that it just printed out on the screen. Be prepared."


function test_command {
    THE_COMMAND=$1
    if [ -n "$3" ]; then
       THE_OUTPUT=`$2 --args "$3"`
    else
       THE_OUTPUT=`$2`
    fi
    RETURN_VAL=$?
    THE_RESULT=$( printf '%03d' ${RETURN_VAL} )
    if [ ${RETURN_VAL} = 0 ]; then
       echo "${THE_COMMAND} returned zero. (Success.)"
    else
       echo "${THE_COMMAND} returned: ${RETURN_VAL}   (0 is success)"
    fi

    echo "-----------------------------------------"
    echo "Output:"
    echo ""
    echo "${THE_OUTPUT}"
    echo ""
    echo "(Finished ${THE_COMMAND}) Press enter to continue..."
    read CONTINUE
}

# -----------------------------------------------------------------------------------------
# Cash

#withdraw       withdraw cash. (From acct on server into local purse.)
COMPLEX_COMMAND='opentxs withdraw --myacct '${FTACCT}''
ARGS='amount 42'
test_command "withdraw" "${COMPLEX_COMMAND}" "${ARGS}"

#showpurse      show contents of cash purse.
test_command "showpurse" "opentxs showpurse --mynym ${FTNYM} --server ${SERVER} --mypurse ${SILVERPURSE}"

#exportcash     export a cash purse.
COMPLEX_COMMAND='opentxs exportcash --mypurse '${SILVERPURSE}' --mynym '${FTNYM}' --hisnym '${BOBNYM}' --server '${SERVER}''
ARGS='memo "Test export cash memo. " amount 42'
test_command "export" "${COMPLEX_COMMAND}" "${ARGS}"

#showpurse      show contents of cash purse.
test_command "showpurse" "opentxs showpurse --mynym ${FTNYM} --server ${SERVER} --mypurse ${SILVERPURSE}"

#importcash     import a cash purse.
COMPLEX_COMMAND='opentxs importcash --mynym '${BOBNYM}''
test_command "importcash" "${COMPLEX_COMMAND}"

#showpurse      show contents of cash purse.
test_command "showpurse" "opentxs showpurse --mynym ${BOBNYM} --server ${SERVER} --mypurse ${SILVERPURSE}"

# --------------------------------------------------------------------------------------------
# Vouchers

#withdrawvoucher     withdraw from myacct as a voucher (cashier's cheque.)
COMPLEX_COMMAND='opentxs buyvoucher --myacct '${FTACCT}' --hisnym '${BOBNYM}''
ARGS='memo "Test withdraw voucher memo. " amount 3'
test_command "buyvoucher" "${COMPLEX_COMMAND}" "${ARGS}"

#deposit		deposit cash, cheque, voucher, or tokens.
COMPLEX_COMMAND='opentxs deposit --myacct '${BOBACCT}' --mynym '${BOBNYM}''
test_command "deposit" "${COMPLEX_COMMAND}"

# --------------------------------------------------------------------------------------------
# Cheques
#

#writecheque	write a cheque and print it out to the screen.
COMPLEX_COMMAND='opentxs writecheque --myacct '${FTACCT}' --hisnym '${BOBNYM}''
ARGS='memo "Test write cheque memo. " amount 10 validfor 2592000'
test_command "writecheque" "${COMPLEX_COMMAND}" "${ARGS}"

#deposit		deposit cash, cheque, voucher, or tokens.
COMPLEX_COMMAND='opentxs deposit --myacct '${BOBACCT}' --mynym '${BOBNYM}''
test_command "deposit" "${COMPLEX_COMMAND}"

#
# Invoices
#

#writeinvoice	write an invoice and print it out to the screen.
COMPLEX_COMMAND='opentxs writeinvoice --myacct '${FTACCT}' --hisnym '${BOBNYM}''
ARGS='memo "Test write invoice memo. " amount 1 validfor 2592000'
test_command "writeinvoice" "${COMPLEX_COMMAND}" "${ARGS}"

#deposit		deposit cash, cheque, voucher, or tokens.
COMPLEX_COMMAND='opentxs deposit --myacct '${BOBACCT}' --mynym '${BOBNYM}''
test_command "deposit" "${COMPLEX_COMMAND}"

# -------------------------------------------------------------------------------------------
