/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public class OTPasswordData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OTPasswordData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OTPasswordData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_OTPasswordData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean isForNormalNym() {
    return otapiJNI.OTPasswordData_isForNormalNym(swigCPtr, this);
  }

  public boolean isForMasterKey() {
    return otapiJNI.OTPasswordData_isForMasterKey(swigCPtr, this);
  }

  public String GetDisplayString() {
    return otapiJNI.OTPasswordData_GetDisplayString(swigCPtr, this);
  }

  public boolean isUsingOldSystem() {
    return otapiJNI.OTPasswordData_isUsingOldSystem(swigCPtr, this);
  }

  public void setUsingOldSystem(boolean bUsing) {
    otapiJNI.OTPasswordData_setUsingOldSystem__SWIG_0(swigCPtr, this, bUsing);
  }

  public void setUsingOldSystem() {
    otapiJNI.OTPasswordData_setUsingOldSystem__SWIG_1(swigCPtr, this);
  }

  public OTPassword GetMasterPW() {
    long cPtr = otapiJNI.OTPasswordData_GetMasterPW(swigCPtr, this);
    return (cPtr == 0) ? null : new OTPassword(cPtr, false);
  }

  public OTPasswordData(String szDisplay, OTPassword pMasterPW) {
    this(otapiJNI.new_OTPasswordData__SWIG_0(szDisplay, OTPassword.getCPtr(pMasterPW), pMasterPW), true);
  }

  public OTPasswordData(String szDisplay) {
    this(otapiJNI.new_OTPasswordData__SWIG_1(szDisplay), true);
  }

  public OTPasswordData(SWIGTYPE_p_OTString strDisplay, OTPassword pMasterPW) {
    this(otapiJNI.new_OTPasswordData__SWIG_4(SWIGTYPE_p_OTString.getCPtr(strDisplay), OTPassword.getCPtr(pMasterPW), pMasterPW), true);
  }

  public OTPasswordData(SWIGTYPE_p_OTString strDisplay) {
    this(otapiJNI.new_OTPasswordData__SWIG_5(SWIGTYPE_p_OTString.getCPtr(strDisplay)), true);
  }

}
