/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum StoredObjectType {
  STORED_OBJ_STRING = 0,
  STORED_OBJ_BLOB,
  STORED_OBJ_STRING_MAP,
  STORED_OBJ_WALLET_DATA,
  STORED_OBJ_BITCOIN_ACCT,
  STORED_OBJ_BITCOIN_SERVER,
  STORED_OBJ_RIPPLE_SERVER,
  STORED_OBJ_LOOM_SERVER,
  STORED_OBJ_SERVER_INFO,
  STORED_OBJ_CONTACT_NYM,
  STORED_OBJ_CONTACT_ACCT,
  STORED_OBJ_CONTACT,
  STORED_OBJ_ADDRESS_BOOK,
  STORED_OBJ_MARKET_DATA,
  STORED_OBJ_MARKET_LIST,
  STORED_OBJ_BID_DATA,
  STORED_OBJ_ASK_DATA,
  STORED_OBJ_OFFER_LIST_MARKET,
  STORED_OBJ_TRADE_DATA_MARKET,
  STORED_OBJ_TRADE_LIST_MARKET,
  STORED_OBJ_OFFER_DATA_NYM,
  STORED_OBJ_OFFER_LIST_NYM,
  STORED_OBJ_TRADE_DATA_NYM,
  STORED_OBJ_TRADE_LIST_NYM,
  STORED_OBJ_ERROR
}
