/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Storable : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Storable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Storable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Storable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otapiPINVOKE.delete_Storable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public static Storable Create(StoredObjectType eType, PackType thePackType) {
    IntPtr cPtr = otapiPINVOKE.Storable_Create((int)eType, (int)thePackType);
    Storable ret = (cPtr == IntPtr.Zero) ? null : new Storable(cPtr, false);
    return ret;
  }

  public static Storable ot_dynamic_cast(Storable pObject) {
    IntPtr cPtr = otapiPINVOKE.Storable_ot_dynamic_cast(Storable.getCPtr(pObject));
    Storable ret = (cPtr == IntPtr.Zero) ? null : new Storable(cPtr, false);
    return ret;
  }

}
