/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#ifndef SWIG_otapi_WRAP_H_
#define SWIG_otapi_WRAP_H_

class SwigDirector_OTCallback : public OTCallback
{
 public:
  SwigDirector_OTCallback(void *swig_p);
  virtual ~SwigDirector_OTCallback();
  void _swig_upcall_runOne(char const *szDisplay, OTPassword &theOutput) {
    OTCallback::runOne(szDisplay,theOutput);
  }
  virtual void runOne(char const *szDisplay, OTPassword &theOutput);
  void _swig_upcall_runTwo(char const *szDisplay, OTPassword &theOutput) {
    OTCallback::runTwo(szDisplay,theOutput);
  }
  virtual void runTwo(char const *szDisplay, OTPassword &theOutput);
 private:
  void *go_val;
};

#endif
